mysite/urls.py
from django.urls import path
from .views import *

app_name = 'mysite'
urlpatterns = [
	path('',index, name='index'),
	path('main/',mainpage, name='mainpage'),
	path('message_me/',message, name='message'),

    path('registration/',registration, name='registration'),
    path('registration/verification',email_verification, name="email_verification"),
    path('registration/add_subscriber/',add_subscriber, name='add_subscriber'),
    path('registration/unsubscribe/<email>/<password>/',unsubscribe, name='unsubscribe'),


    path('schedule_form/',schedule_form,name='schedule_form'),
    path('schedule_reset/',schedule_reset,name='schedule_reset'),
    path('schedule/',schedule_view, name='schedule_view'),
]

pepewtest/urls.py
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static 
import landing_page.urls as landing_page
import mysite.urls as mysite
import my_library.urls as my_library

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(landing_page)),
    path('welcome/',include(mysite)),
    path('my_library/',include(my_library,namespace="my_library"),name="my_library"),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/models.py
from django.db import models
from datetime import date,time

# Create your models here.
class Schedule(models.Model):
	date = models.DateField()
	time = models.TimeField()
	event = models.CharField(max_length=25)
	venue = models.CharField(max_length=50)
	category = models.CharField(max_length=10)

class Registration(models.Model):
	email = models.EmailField()
	name = models.CharField(max_length=50)
	password = models.CharField(max_length=30)

mysite/forms.py
from django import forms

class Schedule_Form(forms.Form):
	date = forms.DateField(label='Date', required=True, widget=forms.DateInput(attrs={'type' : 'date'}))
	time = forms.TimeField(label='Time', required=True, widget=forms.TimeInput(attrs={'type' : 'time'}))
	event = forms.CharField(label='Event', required=True, max_length=25)
	venue = forms.CharField(label='Venue', required=True, max_length=50)
	category = forms.CharField(label='Category', required=True, max_length=10)

class Registration_Form(forms.Form):
	name = forms.CharField(
		label='Name',
		# required=True,
		max_length=50, 
		widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'width' : ' 30%', 
				'id' : 'name-field',
				'placeholder' : 'John Doe'
			}
		)
	)
	email = forms.EmailField(
		label='Email',
		# required=True, 
		widget=forms.TextInput(
			attrs={
				'class' : 'form-control', 
				'width' : ' 30%', 
				'id' : 'email-field',
				'placeholder' : 'example@email.com'
			}
		)
	)
	password = forms.CharField(label='Password',
		# required=True,
		widget=forms.PasswordInput(
			attrs={
				'class' : 'form-control', 
				'width' : ' 30%',
				'id' : 'password-field',
				'placeholder' : 'Password'
			}
		)
	)

mysite/views.py
from django.shortcuts import render,redirect
from .models import Schedule, Registration
from .forms import Schedule_Form, Registration_Form
from django.core.validators import validate_email
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

# Create your views here.
def index(request):
    return render(request,'Story03WelcomePage.html',{})

def mainpage(request):
	return render(request,'Story03.html',{})	

def thanks_regist(request):
	return render(request,'thanks.html')

def message(request):
	return render(request,'Story03Challenge.html')

def registration(request):
	form = Registration_Form(request.POST or None)
	response = {}
	response['form'] = form
	return render(request,'Registration.html',response)

@csrf_exempt
def add_subscriber(request):
	print('post')
	if (request.method == 'POST'):
		enctype = "multipart/form-data"
		name = request.POST.get("name")
		email = request.POST.get("email")
		password = request.POST.get("password")
		registration = Registration(name=name,email=email,password=password)
		registration.save()

		data = model_to_dict(registration)

		return HttpResponse(data) 
	else:
		registeredAccounts = Registration.objects.all().values()
		account_list = list(registeredAccounts)
		return JsonResponse(account_list, safe = False)

def model_to_dict(obj):
	data =	serializers.serialize('json',[obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]['fields'])
	return data


@csrf_exempt
def email_verification(request):
	email_valid = False
	if(request.method == 'POST'):
		email = request.POST.get('email')
		
		if(len(email)>=1): 
			email_valid = True

		data = {'is_taken' : Registration.objects.filter(email = email).exists(), 'is_valid' : email_valid}
		return JsonResponse(data)

@csrf_exempt
def unsubscribe(request,email,password):
	if request.method == 'POST':
		email = request.POST['email']
		print(email)
		sub = Registration.objects.get(email=email)
		print('sub')

		if sub.password == password:
			print('berhasil')
			sub.delete()
			return JsonResponse({})

		else:
			print('gagal')
			return JsonResponse({})
	else:
		return HttpResponse({})


def schedule_form(request):
	form = Schedule_Form(request.POST or None)
	response = {}	
	if (request.method == 'POST'):
		if(form.is_valid()):
			response['event'] = request.POST.get("event")
			response['date'] = request.POST.get("date")
			response['time'] = request.POST.get("time")
			response['venue'] = request.POST.get("venue")
			response['category'] = request.POST.get("category")
			schedule = Schedule(date=response['date'],time=response['time'],event=response['event'],venue=response['venue'],category=response['category'])
			schedule.save()
	response['form'] = form
	return render(request,"ScheduleForm.html", response)		
			


def schedule_view(request):
	schedule = Schedule.objects.all()
	response = {
		"jadwal" : schedule
	}
	return render(request, 'ScheduleView.html', response)

def schedule_reset(request):
	Schedule.objects.all().delete()
	return render(request, 'ScheduleView.html', {})

mysite/templates/Registration.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Rafif's Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'MySiteStyle.css' %}">	
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'datatables.min.css' %}">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>


</head>

<body style="height: ">
	<div id="content">
    <!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'mysite:index' %}"> <img src="{% static "Logo.png" %}" style="width:50px;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			 		 <a class="nav-link" href="{% url 'mysite:mainpage' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:message' %}">Message Me</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_form' %}">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_view' %}">My Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:registration' %}">Subscribe</a>
			  	</li>
		  	</ul>
		</div>
	</nav>

	<div style="text-align: center;">
		<a href="{% url 'mysite:mainpage' %}">
			<img src="{% static 'Logo.png' %}" class="logo">	
		</a>
	</div>
<br>

<!-- Form section -->
<section name='form' class="form-regis">
	<br>
	<div class="form-regis">
	<p style="text-align: center; font-size: 30px; color: white">Subscription  Form</p><br>
		<form id="form" method="POST" onsubmit="postform()">
			{% csrf_token %}
			<div class="form-group">
				<label style="color: white">{{ form.name.label }}</label><br>
				{{ form.name }}
			</div>
			<div class="form-group">
				<label style="color: white">{{ form.email.label }}</label><br>
				{{ form.email }}
			</div>
			<small id="emailHelp" class="form-text" style="color: white"></small>
			<br>
			<div class="form-group">
				<label style="color: white">{{ form.password.label }}</label><br>
				{{ form.password }}
			</div>
			<button type="submit" class="btn btn-primary" id="submit-btn">Submit</button>
		</form>
		<br>
	</div>
</section>

<br><br>

<!-- List section -->
<div style="text-align: center;">
	<h2>~ Subscriber List ~</h2>
</div>

<br>

<div style="margin-left: 10%;margin-right: 10%">
  <table id="table" class="table table-hover table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead class="thead-dark">
    <tr>
    	<th class="th-sm">No
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Nama
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Email
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Unsubscribe
      </th>
    </tr>
  </thead>
</table>
</div>

<div class="jumbotron footer">
  		<div class="container">
    		<h2 style="text-align: center;color: white">Want to know more about me?</h2>
    		<svg height="10" width="70%" style="margin-left: 1%;">
	  		<line x1="45%" y1="0" x2="95%" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<br><br>
    		<div class="container">
			  	<div class="row">
			    	<div class="col-sm">
			      		<img src="https://pbs.twimg.com/media/DnfEqdBVAAAIeiD.png" class="align-self-center mr-3 socmedLogo">
			      		<p id="socmedID">@rafiftaris</p>
			    	</div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdCV4AAjnr0.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">@rafiftaris</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqczUcAEE1A-.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">rafiftaris1@gmail.com</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdBV4AA73Jp.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">Rafif Taris</p>
				    </div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Email Validation Webservice -->
<script type="text/javascript">
	var email_valid = false;
	var email = document.getElementById('email-field');
	var timeout = null;

	email.onkeyup = function(e){
		clearTimeout(timeout);
		timeout = setTimeout(function(){
			console.log('start verification')
			$.ajax({
				method : "POST",
				url : "{% url 'mysite:email_verification' %}",
				data : {
					"email" : email.value
				},
				success : function(data){
					if(data.is_taken){
						console.log('email taken');
						$("#emailHelp").text('Email has been taken. Please register another email.');
					}
					else{
						if(data.is_valid){
							console.log('email available');
							$("#emailHelp").text('Email available.');
							email_valid = true;
						}
					}
				}
			})
		},1000);
	}

	function postform(){
		console.log('MASHOOOK')
		$.ajax({
			type:'POST',
			url:"{% url 'mysite:add_subscriber' %}",
			data:{ 
				name: $('#name-field').val(),
				email: $('#email-field').val(),
				password: $('#password-field').val(),
			},
			success: function(){
				alert("Terimakasih telah mendaftar jadi subscriber.")
				window.location.reload();
			},
		})
	}

	function display_list(){
		$.ajax({
			type:'GET',
			url:"{% url 'mysite:add_subscriber' %}",
			success: function(result){
				var acc_list = result;
				jsontoHTML(acc_list);
			},
		});
	}

	function jsontoHTML(acc_list){
		var table = document.getElementById("table");
		htmlString = "<tbody>";
		for(var i = 0;i<acc_list.length;i++){
			htmlString += "<tr>" +
			"<td><p>" + (i+1) + "</p></td>" +
			"<td><p>" + acc_list[i].name + "</p></td>" +
			'<td><p  id="email-'+ i +'">' + acc_list[i].email + "</p></td>" +
			"<td>" + '<button class="btn btn-danger" onclick=unsubscribe(this.id) id="'+ i +'">Unsubscribe</button>' + "</td>" +
			"</tr>";
		}
		table.insertAdjacentHTML('beforeend',htmlString + "</tbody>")
		$('#table').DataTable();
		$('.dataTables_length').addClass('bs-select');
	}

	function unsubscribe(id){
		var email = $('#email-' + id).text();
		console.log(email);
		validate(email)
	}

	function validate(email){
		var password = prompt("Insert password to unsubscribe")
		console.log(password);
		$.ajax({
			method:'POST',
			data:{
				email : email,
				password : password
			},
			url : "unsubscribe/" + email + "/" + password + "/",
			success : function(){
				console.log('horee');
				window.location.reload();
			}
		});
	};
	

	$(document).ready(function(){
		console.log('ready')
		display_list();
		validation();
		$('#name-field, #email-field, #password-field').change(validation);

		function validation(){
			console.log('validation')
			if(email_valid == true && $('#name-field').val().length>0 && $('#email-field').val().length>0 && $('#password-field').val().length>0){
				console.log('can submit');
				$("#submit-btn").attr("disabled",false);
			}
			else{
				console.log('cant submit');
				$("#submit-btn").attr("disabled",true); 
			} 
		}
	});
</script>

</body>
</html>

mysite/templates/ScheduleForm.html
{% extends 'base.html' %}

{% block content %}
<br>
<section name="form" style="text-align: center;">
		<p style="text-align: center; font-size: 30px;">~ Schedule Form ~</p><br>
		<form id="form" method="POST" action="{% url 'mysite:schedule_form' %}">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group">
			    <label for="exampleInputName1">{{ field.label }}<br>
			    {{ field }}
			    </label>
			</div>
			{% endfor %}
			<br>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
</section>
{% endblock %}

mysite/templates/ScheduleView.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<br>
<p style="text-align: center; font-size: 30px;">~ My Schedule ~</p>
<br>

	{% if jadwal %}
		<div style="text-align: center;">
			<button type="button" class="btn btn-danger" onclick="location.href='{% url 'mysite:schedule_reset' %}'">Delete Schedule</button>
		</div>
		{% for acara in jadwal %}
		<br>
		<div class='rcorners1'>
			<br>
			<p>&ensp;{{ acara.event }}</p>
			<p>&ensp;Date     : {{ acara.date }}</p>
			<p>&ensp;Time     : {{ acara.time }}</p>
			<p>&ensp;Venue    : {{ acara.venue }}</p>
			<p>&ensp;Category : {{ acara.category }}</p>
		</div>
		{% endfor %}
	{% else %}
	<br><br>
	<p style="text-align: center;font-size: 30px;">Belum ada jadwal</p>
	{% endif %}

{% endblock %}

mysite/templates/Story03Challenge.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<br>
	<p style="text-align: center; font-size: 30px;">~ Registration Form ~</p>
	<div style="text-align: center; display: none; font-size: 20px" id="thanks">Thank you for registering yourself at this website!</div><br>
	<form style="text-align: center;">
	  <div class="form-group">
	    <label for="exampleInputName1">Nama</label>
	    <input type="text" class="form-control" id="exampleInputName1" placeholder="Nama" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputDate1">Tanggal Lahir</label>
	    <input type="date" class="form-control" id="exampleInputDate1" aria-describedby="dateHelp" placeholder="dd/mm/yyyy" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputEmail1">Email Address</label>
	    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" style="width: 30%; margin: 0% 35% 0% 35%;">
	    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
	  </div>
	  <div class="form-group">
	    <label for="exampleInputUsername1">Username</label>
	    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Username" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password</label>
	    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Password Confirmation</label>
	    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password Confirmation" style="width: 30%; margin: 0% 35% 0% 35%;">
	  </div>
	  <button type="submit" class="btn btn-primary" style="margin-left: 0.2%" onclick="appear()">Submit</button>
	</form>

	<script type="text/javascript">
		function appear(){
			document.getElementById("thanks").display = block;
		}
	</script>
	<br><br>
{% endblock %}

mysite/templates/Story03WelcomePage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<br>
	<div>
		<h1 style="font-family: 'Playball', cursive; text-align: center; font-size: 10vw;">Welcome!</h1>
	</div>
	<div>
		<img src="https://pbs.twimg.com/media/DnfVh_NVsAA307u.jpg" class="welcomeimg">
	</div>
	<br><br><br>
	<div class="container">
    		<div class="container">
			  <div class="row">
			    <div class="col-sm">
			      	<a href="{% url 'mysite:mainpage' %}" type="button" class="btn btn-light btn-lg welcomebutton" style="margin-bottom: 5%">
						<p class="buttondesc">&ensp;About Me&ensp;
						 <svg height="100" width="50">
			 			 	<polygon points="0,0 35,50 0,100 20, 50"  style="fill:#107551;stroke-width:1;float: right;" />
						 </svg> 
						</p>
					</a>
			    </div>
			    <div class="col-sm">
			      	<a href="{% url 'mysite:registration' %}" type="button" class="btn btn-light btn-lg welcomebutton">
						<p class="buttondesc">&ensp;Register Yourself&ensp;
						 <svg height="100" width="50">
			 			 	<polygon points="0,0 35,50 0,100 20, 50"  style="fill:#107551;stroke-width:1;float: right;" />
						 </svg> 
						</p>
					</a>
			    </div>
			</div>
		</div>
	</div>
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>Rafif's Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'MySiteStyle.css' %}">	
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="{% static 'js/base.js' %}"></script>
</head>

<body style="height: ">
	<div class="loader">
		<div title="text" style="text-align: center;">
			<p style="font-size: 75px;color: white">Welcome to My Website!</p>
			<p style="font-size: 75px;color: white">Please Wait...</p>
		</div>
		<div class='progress progress-striped active'>
			<div class='progress-bar progress-bar-color' id='bar' role='progressbar' style='width: 0%;'></div>
		</div>
	</div>

	<div id="content">
    <!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'mysite:index' %}"> <img src="{% static "Logo.png" %}" style="width:50px;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			 		 <a class="nav-link" href="{% url 'mysite:mainpage' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:message' %}">Message Me</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_form' %}">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:schedule_view' %}">My Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'mysite:registration' %}">Subscribe</a>
			  	</li>
		  	</ul>
		</div>
	</nav>

	<div style="text-align: center;">
		<a href="{% url 'mysite:mainpage' %}">
			<img src="{% static 'Logo.png' %}" class="logo">	
		</a>
	</div>
    {% block content %}
    {% endblock %}
    <div class="jumbotron footer">
  		<div class="container">
    		<h2 style="text-align: center;color: white">Want to know more about me?</h2>
    		<svg height="10" width="70%" style="margin-left: 1%;">
	  		<line x1="45%" y1="0" x2="95%" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<br><br>
    		<div class="container">
			  	<div class="row">
			    	<div class="col-sm">
			      		<img src="https://pbs.twimg.com/media/DnfEqdBVAAAIeiD.png" class="align-self-center mr-3 socmedLogo">
			      		<p id="socmedID">@rafiftaris</p>
			    	</div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdCV4AAjnr0.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">@rafiftaris</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqczUcAEE1A-.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">rafiftaris1@gmail.com</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdBV4AA73Jp.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">Rafif Taris</p>
				    </div>
				</div>
				{% block footer %}
				{% endblock %}
			</div>
		</div>
	</div>
</div>
</body>
</html>

mysite/templates/thanks.html
{% extends 'logoNavbar.html' %}

{% block content %}
<br>
<div class="container quote-box">
	<h2>Terimakasih sudah registrasi di halaman saya.</h2>
</div>

{% endblock %}