my_library/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import *
from django.contrib.auth import views

app_name = 'my_library'
urlpatterns = [
	path('', my_library,name='my_library'),
	path('data/<keyword>/', book_data, name='book_data'),
	path('add/', addFav, name='addFav'),
	path('remove/', removeFav, name='removeFav'),
	path('login/', views.LoginView, name='login'),
 	path('logout/', log_out, name='logout'),
]

mysite/urls.py
from django.urls import path
from .views import *

app_name = 'mysite'
urlpatterns = [
	path('',index, name='index'),
	path('main/',mainpage, name='mainpage'),
	path('message_me/',message, name='message'),

    path('registration/',registration, name='registration'),
    path('registration/verification',email_verification, name="email_verification"),
    path('registration/add_subscriber/',add_subscriber, name='add_subscriber'),
    path('registration/unsubscribe/<email>/<password>/',unsubscribe, name='unsubscribe'),


    path('schedule_form/',schedule_form,name='schedule_form'),
    path('schedule_reset/',schedule_reset,name='schedule_reset'),
    path('schedule/',schedule_view, name='schedule_view'),
]

pepewtest/urls.py
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static 
import landing_page.urls as landing_page
import mysite.urls as mysite
import my_library.urls as my_library

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(landing_page)),
    path('welcome/',include(mysite)),
    path('my_library/',include(my_library,namespace="my_library"),name="my_library"),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_library/models.py
from django.db import models

# Create your models here

my_library/views.py
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render
from .models import *
import requests
import urllib.request, json
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
	return render(request,'index.html')

def book_data(request,keyword):
	URL = "https://www.googleapis.com/books/v1/volumes?q=" + keyword
	getJson = requests.get(URL)
	data = getJson.json()
	if request.user.is_authenticated:
		counter = request.session.get('counter', 0)
		request.session['counter'] = counter
		for key, value in request.session.items():
			print('{} => {}'.format(key, value))
	return JsonResponse(data)

def log_out(request):
	logout(request)
	return HttpResponseRedirect('/my_library/')

def addFav(request):
	print(dict(request.session))
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type = 'application/json')

def removeFav(request):
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type = 'application/json')

def my_library(request):
	response={'counter' : 0}
	if request.user.is_authenticated:
		request.session['user'] = request.user.username
		request.session['email'] = request.user.email
		counter = request.session.get('counter', 0)
		print(dict(request.session))
		response = {'counter' : counter}
		for key, value in request.session.items():
			print('{} => {}'.format(key, value))
	return render(request,'my_library.html',response)

my_library/templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/Article">

<head>
	<title>Rafif's Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="google-signin-client_id" content="1066754825400-3mdp8a6s97k98cg0m9vcfapsdk9rtmu2.apps.googleusercontent.com">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link href="https://fonts.googleapis.com/css?family=Reem+Kufi" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'LibraryStyle.css' %}">	
	<link rel="stylesheet" href="{% static 'datatables.min.css' %}">	


	<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="https://apis.google.com/js/platform.js" async defer></script>
	<script type="text/javascript">
		function start() {
			gapi.load('auth2', function() {
			auth2 = gapi.auth2.init({
			  client_id: '1066754825400-3mdp8a6s97k98cg0m9vcfapsdk9rtmu2.apps.googleusercontent.com',
			  // Scopes to request in addition to 'profile' and 'email'
			  //scope: 'additional_scope'
			});
		});
	}
	</script>

<!-- 	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
<!--     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->

</head>

<body style="height: ">
	<div class="loader">
		<div title="text" style="text-align: center;">
			<p style="font-size: 75px;color: white">Welcome to My Website!</p>
			<p style="font-size: 75px;color: white">Please Wait...</p>
		</div>
		<div class='progress progress-striped active'>
			<div class='progress-bar progress-bar-color' id='bar' role='progressbar' style='width: 0%;'></div>
		</div>
	</div>

	<div id="content">
    <!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'mysite:mainpage' %}"> <img src="{% static "Logo.png" %}" style="width:50px;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			 		 <a class="nav-link" href="{% url 'mysite:mainpage' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link">Message Me</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link">My Schedule</a>
			  	</li>
		  	</ul>

		  	{% if user.is_authenticated %}
        		<a href="{% url 'my_library:logout'%}"><button type="button" class="btn btn-danger" id="signOut" style="float:right">Sign out</button></a>
        	{% else %}
        		<a style="color:black" href="{% url 'social:begin' 'google-oauth2' %}">Sign in with Google</a>
   			{% endif %}
			
			<button type="button" class="btn btn-danger" id="signOut" style="float:right; display: none">Sign out</button>
		</div>
	</nav>

	<div style="text-align: center;">
		<a href="{% url 'mysite:mainpage' %}">
			<img src="{% static 'Logo.png' %}" class="logo">	
		</a>
	</div>
	<br><br>
	{% if user.is_authenticated %}
        <p class="display-4" style="text-align: center;">Hello, {{ user.first_name }}!</p>
    {% endif %}

    {% block content %}
    {% endblock %}
    <div class="jumbotron footer">
  		<div class="container">
    		<h2 style="text-align: center;color: white">Want to know more about me?</h2>
    		<svg height="10" width="70%" style="margin-left: 1%;">
	  		<line x1="45%" y1="0" x2="95%" y2="0" style="stroke:#56CCF2 ;stroke-width:20;" />
	  		Sorry, your browser does not support inline SVG.
			</svg>
			<br><br>
    		<div class="container">
			  	<div class="row">
			    	<div class="col-sm">
			      		<img src="https://pbs.twimg.com/media/DnfEqdBVAAAIeiD.png" class="align-self-center mr-3 socmedLogo">
			      		<p id="socmedID">@rafiftaris</p>
			    	</div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdCV4AAjnr0.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">@rafiftaris</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqczUcAEE1A-.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">rafiftaris1@gmail.com</p>
				    </div>
				    <div class="col-sm">
				      <img src="https://pbs.twimg.com/media/DnfEqdBV4AA73Jp.png" class="align-self-center mr-3 socmedLogo">
				      <p id="socmedID">Rafif Taris</p>
				    </div>
				</div>
				{% block footer %}
				{% endblock %}
			</div>
		</div>
	</div>
</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- MDBootstrap Datatables  -->
	<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
	<script src="{% static 'js/basic.js' %}"></script>
</body>
</html>

my_library/templates/index.html
{% extends 'base_template.html' %}
{% load static %}

{% block content %}
<br><br>
<div style="text-align: center">
	<h1>You must sign in to access the library</h1>
	<br>
</div>
<script>
	function start() {
		gapi.load('auth2', function() {
			auth2 = gapi.auth2.init({
			  client_id: 'YOUR_CLIENT_ID.apps.googleusercontent.com',
			  // Scopes to request in addition to 'profile' and 'email'
			  //scope: 'additional_scope'
			});
		});
	}
	function onSignIn(googleUser) {
		var profile = googleUser.getBasicProfile();
		console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
		console.log('Name: ' + profile.getName());
		console.log('Image URL: ' + profile.getImageUrl());
		console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
		window.location.href = "{% url 'my_library:my_library' %}"
	}

</script>

{% endblock %}

my_library/templates/my_library.html
{% extends 'base_template.html' %}
{% load static %}

{% block content %}
<br><br>

<div style="text-align: center;">
	<h2>~ My Library ~</h2>
</div>
<br><br>

<div class="input-group input-group-lg">
  <input id="input" name="search-category" type="text" class="form-control" aria-label="Large" aria-describedby="inputGroup-sizing-sm" placeholder="Search your book category here..." style="margin-left: 10%">
  <div class="input-group-append"style="margin-right: 10%">
    <button id="search-button" class="btn btn-outline-secondary" type="button" onclick="searchBook()">Search</button>
  </div>
</div>

<br><br>

<h3 id='notif' style="color:red; text-align: center; display: none">Sign in first to add favorite</h3>

<div style="margin-left: 10%;margin-right: 10%">
  <h3>Favorite book(s) : <span id="fav-counter">{{ counter }}</span></h3>
  <table id="table" class="table table-hover table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead class="thead-dark">
    <tr>
      <th class="th-sm">
      </th>
      <th class="th-sm">Book Title
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Author
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Publisher
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Published Date
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
      <th class="th-sm">Favorite
        <i class="fa fa-sort float-right" aria-hidden="true"></i>
      </th>
    </tr>
  </thead>
     <!--  <tbody>
        {% for book in response %} 
        <tr>
          <td><img src="{{ book.imageLink }}"></td>
          <td>{{ book.title }}</td>
          <td>{{ book.authors }}</td>
          <td>{{ book.publisher }}</td>
          <td>{{ book.publishedDate }}</td>
          <td><button class="btn" onclick=favorite(this.id) id="{{ book.id }}"><i class="fa fa-star"></i></button></td>
        </tr>
        {% endfor %}
      </tbody> -->
	</table>
  <script src="{% static 'js/library.js' %}"></script>
</div>
{% endblock %}